services:
  usermanagement:
    image: usermanagement
    build:
      context: .
      dockerfile: UserManagement/Dockerfile

  chattingmanagement:
    image: chattingmanagement
    build:
      context: .
      dockerfile: ChattingManagement/Dockerfile

  courtmanagement:
    image: courtmanagement
    build:
      context: .
      dockerfile: CourtManagement/Dockerfile

  notificationmanagement:
    image: notificationmanagement
    build:
      context: .
      dockerfile: NotificationManagement/Dockerfile

  matchmanagement:
    image: matchmanagement
    build:
      context: .
      dockerfile: MatchManagement/Dockerfile

  bookingmanagement:
    image: bookingmanagement
    build:
      context: .
      dockerfile: BookingManagement/Dockerfile
